
namespace Kahuna.Server.ScriptParser;

/// <summary>
/// Represents various types of nodes used in script parsing and execution contexts.
/// </summary>
public enum NodeType
{
    NullType,
    IntegerType,
    StringType,
    FloatType,
    BooleanType,
    Identifier,
    Placeholder,
    StmtList,
    Let,
    Set,
    Get,
    Exists,
    Delete,
    Extend,
    GetByPrefix,
    Eset,
    Eget,
    Eexists,
    Edelete,
    Eextend,
    EgetByPrefix,
    If,
    For,
    Equals,
    NotEquals,
    LessThan,
    GreaterThan,
    LessThanEquals,
    GreaterThanEquals,
    And,
    Or,
    Not,
    Add,
    Subtract,
    Mult,
    Div,
    Range,
    ArrayIndex,
    FuncCall,
    ArgumentList,
    NotSet,
    NotFound,
    SetNotExists,
    SetExists,
    SetCmp,
    SetCmpRev,
    Begin,
    BeginOptionList,
    BeginOption,
    Rollback,
    Commit,
    Return,
    Sleep,
    Throw,
}