//
//  This CSharp output file generated by Gardens Point LEX
//  Gardens Point LEX (GPLEX) is Copyright (c) John Gough, QUT 2006-2014.
//  Output produced by GPLEX is the property of the user.
//  See accompanying file GPLEXcopyright.rtf.
//
//  GPLEX Version:  1.2.3
//  DateTime: 3/18/2025 1:21:20 PM
//  GPLEX input file <ScriptParser/ScriptParser.Language.analyzer.lex - 3/18/2025 1:21:14 PM>
//  GPLEX frame file <embedded resource>
//
//  Option settings: verbose, parser, stack, minimize
//  Option settings: compressNext, persistBuffer, noEmbedBuffers
//

//
// Revised backup code
// Version 1.2.1 of 24-June-2013
//
//
#define BACKUP
#define STACK
#define PERSIST

using System;
using System.IO;
using System.Text;
using System.Globalization;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Diagnostics.CodeAnalysis;

using QUT.GplexBuffers;

namespace Kahuna.Server.ScriptParser
{   
    /// <summary>
    /// Summary Canonical example of GPLEX automaton
    /// </summary>
    
#if STANDALONE
    //
    // These are the dummy declarations for stand-alone GPLEX applications
    // normally these declarations would come from the parser.
    // If you declare /noparser, or %option noparser then you get this.
    //

     internal enum Token
    { 
      EOF = 0, maxParseToken = int.MaxValue 
      // must have at least these two, values are almost arbitrary
    }

     internal abstract class ScanBase
    {
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "yylex")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "yylex")]
        public abstract int yylex();

        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "yywrap")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "yywrap")]
        protected virtual bool yywrap() { return true; }

#if BABEL
        protected abstract int CurrentSc { get; set; }
        // EolState is the 32-bit of state data persisted at 
        // the end of each line for Visual Studio colorization.  
        // The default is to return CurrentSc.  You must override
        // this if you want more complicated behavior.
        public virtual int EolState { 
            get { return CurrentSc; }
            set { CurrentSc = value; } 
        }
    }
    
     internal interface IColorScan
    {
        void SetSource(string source, int offset);
        int GetNext(ref int state, out int start, out int end);
#endif // BABEL
    }

#endif // STANDALONE
    
    // If the compiler can't find the scanner base class maybe you
    // need to run GPPG with the /gplex option, or GPLEX with /noparser
#if BABEL
     internal sealed partial class scriptScanner : ScanBase, IColorScan
    {
        private ScanBuff buffer;
        int currentScOrd;  // start condition ordinal
        
        protected override int CurrentSc 
        {
             // The current start state is a property
             // to try to avoid the user error of setting
             // scState but forgetting to update the FSA
             // start state "currentStart"
             //
             get { return currentScOrd; }  // i.e. return YY_START;
             set { currentScOrd = value;   // i.e. BEGIN(value);
                   currentStart = startState[value]; }
        }
#else  // BABEL
     internal sealed partial class scriptScanner : ScanBase
    {
        private ScanBuff buffer;
        int currentScOrd;  // start condition ordinal
#endif // BABEL
        
        /// <summary>
        /// The input buffer for this scanner.
        /// </summary>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public ScanBuff Buffer { get { return buffer; } }
        
        private static int GetMaxParseToken() {
     System.Reflection.FieldInfo f = typeof(Token).GetField("maxParseToken");
            return (f == null ? int.MaxValue : (int)f.GetValue(null));
        }
        
        static int parserMax = GetMaxParseToken();
        
        enum Result {accept, noMatch, contextFound};

        const int maxAccept = 74;
        const int initial = 75;
        const int eofNum = 0;
        const int goStart = -1;
        const int INITIAL = 0;

#region user code
#endregion user code

        int state;
        int currentStart = startState[0];
        int code;      // last code read
        int cCol;      // column number of code
        int lNum;      // current line number
        //
        // The following instance variables are used, among other
        // things, for constructing the yylloc location objects.
        //
        int tokPos;        // buffer position at start of token
        int tokCol;        // zero-based column number at start of token
        int tokLin;        // line number at start of token
        int tokEPos;       // buffer position at end of token
        int tokECol;       // column number at end of token
        int tokELin;       // line number at end of token
        string tokTxt;     // lazily constructed text of token
#if STACK          
        private Stack<int> scStack = new Stack<int>();
#endif // STACK

#region ScannerTables
    struct Table {
        public int min; public int rng; public int dflt;
        public sbyte[] nxt;
        public Table(int m, int x, int d, sbyte[] n) {
            min = m; rng = x; dflt = d; nxt = n;
        }
    };

    static int[] startState = new int[] {75, 0};

    static Table[] NxS = new Table[85] {
/* NxS[   0] */ new Table(0, 0, 0, null), // Shortest string ""
/* NxS[   1] */ // Shortest string "\t"
      new Table(9, 24, -1, new sbyte[] {1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, 1}),
/* NxS[   2] */ new Table(0, 0, -1, null), // Shortest string "("
/* NxS[   3] */ new Table(0, 0, -1, null), // Shortest string ")"
/* NxS[   4] */ // Shortest string "0"
      new Table(46, 75, -1, new sbyte[] {81, -1, 5, 5, 5, 5, 
          5, 5, 5, 5, 5, 5, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, 82}),
/* NxS[   5] */ // Shortest string "1"
      new Table(46, 12, -1, new sbyte[] {81, -1, 5, 5, 5, 5, 
          5, 5, 5, 5, 5, 5}),
/* NxS[   6] */ // Shortest string "<"
      new Table(61, 2, -1, new sbyte[] {68, 69}),
/* NxS[   7] */ new Table(0, 0, -1, null), // Shortest string "="
/* NxS[   8] */ // Shortest string ">"
      new Table(61, 1, -1, new sbyte[] {67}),
/* NxS[   9] */ // Shortest string "A"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  10] */ // Shortest string "B"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 62, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 62, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  11] */ // Shortest string "C"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 58, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 58, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  12] */ // Shortest string "E"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 9, 
          9, 49, 9, 9, 9, 9, 43, 9, 50, 9, 9, 9, 9, 51, 9, 9, 
          9, 9, 52, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 49, 9, 9, 9, 9, 43, 9, 50, 9, 9, 9, 9, 51, 9, 9, 
          9, 9, 52, 9, 9}),
/* NxS[  13] */ // Shortest string "G"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 47, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 47, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  14] */ // Shortest string "I"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 9, 
          46, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          46, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  15] */ // Shortest string "N"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 42, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 42, 9, 9}),
/* NxS[  16] */ // Shortest string "R"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 30, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 31, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 30, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 31, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  17] */ // Shortest string "S"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 28, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 28, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  18] */ // Shortest string "T"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 9, 
          9, 9, 25, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 25, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  19] */ // Shortest string "X"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 24, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 24, 9, 9}),
/* NxS[  20] */ // Shortest string "e"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 9, 
          9, 49, 9, 9, 9, 9, 9, 9, 50, 9, 9, 9, 9, 51, 9, 9, 
          9, 9, 52, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 49, 9, 9, 9, 9, 9, 9, 50, 9, 9, 9, 9, 51, 9, 9, 
          9, 9, 52, 9, 9}),
/* NxS[  21] */ // Shortest string "l"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 43, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 43, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  22] */ new Table(0, 0, -1, null), // Shortest string "{"
/* NxS[  23] */ new Table(0, 0, -1, null), // Shortest string "}"
/* NxS[  24] */ // Shortest string "XX"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  25] */ // Shortest string "TH"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 26, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 26, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  26] */ // Shortest string "THE"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 27, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 27, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  27] */ // Shortest string "THEN"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  28] */ // Shortest string "SE"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 29, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 29, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  29] */ // Shortest string "SET"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  30] */ // Shortest string "RE"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 38, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 38, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  31] */ // Shortest string "RO"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 32, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 32, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  32] */ // Shortest string "ROL"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 33, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 33, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  33] */ // Shortest string "ROLL"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 34, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 34, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  34] */ // Shortest string "ROLLB"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 35, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 35, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  35] */ // Shortest string "ROLLBA"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 36, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 36, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  36] */ // Shortest string "ROLLBAC"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 37, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 37, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  37] */ // Shortest string "ROLLBACK"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  38] */ // Shortest string "RET"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 39, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 39, 
          9, 9, 9, 9, 9}),
/* NxS[  39] */ // Shortest string "RETU"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 40, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 40, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  40] */ // Shortest string "RETUR"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 41, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 41, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  41] */ // Shortest string "RETURN"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  42] */ // Shortest string "NX"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  43] */ // Shortest string "EL"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 44, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 44, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  44] */ // Shortest string "ELS"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 45, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 45, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  45] */ // Shortest string "ELSE"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  46] */ // Shortest string "IF"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  47] */ // Shortest string "GE"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 48, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 48, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  48] */ // Shortest string "GET"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  49] */ // Shortest string "EG"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 56, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 56, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  50] */ // Shortest string "EN"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 55, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 55, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  51] */ // Shortest string "ES"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 53, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 53, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  52] */ // Shortest string "EX"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  53] */ // Shortest string "ESE"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 54, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 54, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  54] */ // Shortest string "ESET"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  55] */ // Shortest string "END"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  56] */ // Shortest string "EGE"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 57, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 57, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  57] */ // Shortest string "EGET"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  58] */ // Shortest string "CO"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 59, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 59, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  59] */ // Shortest string "COM"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 60, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 60, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  60] */ // Shortest string "COMI"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 61, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 61, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  61] */ // Shortest string "COMIT"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  62] */ // Shortest string "BE"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 9, 
          9, 63, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 63, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  63] */ // Shortest string "BEG"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 64, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 64, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  64] */ // Shortest string "BEGI"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 65, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 65, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  65] */ // Shortest string "BEGIN"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  66] */ // Shortest string "@0"
      new Table(48, 75, -1, new sbyte[] {66, 66, 66, 66, 66, 66, 
          66, 66, 66, 66, -1, -1, -1, -1, -1, -1, -1, 66, 66, 66, 66, 66, 
          66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 
          66, 66, 66, 66, 66, -1, -1, -1, -1, 66, -1, 66, 66, 66, 66, 66, 
          66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 
          66, 66, 66, 66, 66}),
/* NxS[  67] */ new Table(0, 0, -1, null), // Shortest string ">="
/* NxS[  68] */ new Table(0, 0, -1, null), // Shortest string "<="
/* NxS[  69] */ new Table(0, 0, -1, null), // Shortest string "<>"
/* NxS[  70] */ // Shortest string "0.0"
      new Table(48, 10, -1, new sbyte[] {70, 70, 70, 70, 70, 70, 
          70, 70, 70, 70}),
/* NxS[  71] */ // Shortest string "0x0"
      new Table(48, 55, -1, new sbyte[] {71, 71, 71, 71, 71, 71, 
          71, 71, 71, 71, -1, -1, -1, -1, -1, -1, -1, 71, 71, 71, 71, 71, 
          71, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 71, 71, 71, 71, 71, 
          71}),
/* NxS[  72] */ new Table(0, 0, -1, null), // Shortest string "''"
/* NxS[  73] */ new Table(0, 0, -1, null), // Shortest string "\"\""
/* NxS[  74] */ new Table(0, 0, -1, null), // Shortest string "!="
/* NxS[  75] */ // Shortest string ""
      new Table(9, 117, -1, new sbyte[] {1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, 1, 76, 77, -1, -1, -1, -1, 78, 2, 3, -1, -1, -1, 79, -1, 
          -1, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, -1, -1, 6, 7, 8, 
          -1, 80, 9, 10, 11, 9, 12, 9, 13, 9, 14, 9, 9, 9, 9, 15, 
          9, 9, 9, 16, 17, 18, 9, 9, 9, 19, 9, 9, -1, -1, -1, -1, 
          9, -1, 9, 10, 11, 9, 20, 9, 13, 9, 14, 9, 9, 21, 9, 15, 
          9, 9, 9, 16, 17, 18, 9, 9, 9, 19, 9, 9, 22, -1, 23}),
/* NxS[  76] */ // Shortest string "!"
      new Table(61, 1, -1, new sbyte[] {74}),
/* NxS[  77] */ // Shortest string "\""
      new Table(0, 93, 77, new sbyte[] {-1, 77, 77, 77, 77, 77, 
          77, -1, -1, -1, -1, -1, -1, -1, 77, 77, 77, 77, 77, 77, 77, 77, 
          77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 73, 77, 77, 77, 
          77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 
          77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 
          77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 
          77, 77, 77, 77, 77, 77, 84}),
/* NxS[  78] */ // Shortest string "'"
      new Table(0, 93, 78, new sbyte[] {-1, 78, 78, 78, 78, 78, 
          78, -1, -1, -1, -1, -1, -1, -1, 78, 78, 78, 78, 78, 78, 78, 78, 
          78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 
          78, 72, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 
          78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 
          78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 
          78, 78, 78, 78, 78, 78, 83}),
/* NxS[  79] */ // Shortest string "-"
      new Table(48, 10, -1, new sbyte[] {4, 5, 5, 5, 5, 5, 
          5, 5, 5, 5}),
/* NxS[  80] */ // Shortest string "@"
      new Table(48, 75, -1, new sbyte[] {66, 66, 66, 66, 66, 66, 
          66, 66, 66, 66, -1, -1, -1, -1, -1, -1, -1, 66, 66, 66, 66, 66, 
          66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 
          66, 66, 66, 66, 66, -1, -1, -1, -1, 66, -1, 66, 66, 66, 66, 66, 
          66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 
          66, 66, 66, 66, 66}),
/* NxS[  81] */ // Shortest string "0."
      new Table(48, 10, -1, new sbyte[] {70, 70, 70, 70, 70, 70, 
          70, 70, 70, 70}),
/* NxS[  82] */ // Shortest string "0x"
      new Table(48, 55, -1, new sbyte[] {71, 71, 71, 71, 71, 71, 
          71, 71, 71, 71, -1, -1, -1, -1, -1, -1, -1, 71, 71, 71, 71, 71, 
          71, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 71, 71, 71, 71, 71, 
          71}),
/* NxS[  83] */ // Shortest string "'\\"
      new Table(10, 4, 78, new sbyte[] {-1, 78, 78, -1}),
/* NxS[  84] */ // Shortest string "\"\\"
      new Table(10, 4, 77, new sbyte[] {-1, 77, 77, -1}),
    };

int NextState() {
    if (code == ScanBuff.EndOfFile)
        return eofNum;
    else
        unchecked {
            int rslt;
            int idx = (byte)(code - NxS[state].min);
            if ((uint)idx >= (uint)NxS[state].rng) rslt = NxS[state].dflt;
            else rslt = NxS[state].nxt[idx];
            return rslt;
        }
}

#endregion


#if BACKUP
        // ==============================================================
        // == Nested struct used for backup in automata that do backup ==
        // ==============================================================

        struct Context // class used for automaton backup.
        {
            public int bPos;
            public int rPos; // scanner.readPos saved value
            public int cCol;
            public int lNum; // Need this in case of backup over EOL.
            public int state;
            public int cChr;
        }
        
        private Context ctx = new Context();
#endif // BACKUP

        // ==============================================================
        // ==== Nested struct to support input switching in scanners ====
        // ==============================================================

		struct BufferContext {
            internal ScanBuff buffSv;
			internal int chrSv;
			internal int cColSv;
			internal int lNumSv;
		}

        // ==============================================================
        // ===== Private methods to save and restore buffer contexts ====
        // ==============================================================

        /// <summary>
        /// This method creates a buffer context record from
        /// the current buffer object, together with some
        /// scanner state values. 
        /// </summary>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        BufferContext MkBuffCtx()
		{
			BufferContext rslt;
			rslt.buffSv = this.buffer;
			rslt.chrSv = this.code;
			rslt.cColSv = this.cCol;
			rslt.lNumSv = this.lNum;
			return rslt;
		}

        /// <summary>
        /// This method restores the buffer value and allied
        /// scanner state from the given context record value.
        /// </summary>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        void RestoreBuffCtx(BufferContext value)
		{
			this.buffer = value.buffSv;
			this.code = value.chrSv;
			this.cCol = value.cColSv;
			this.lNum = value.lNumSv;
        } 
        // =================== End Nested classes =======================

#if !NOFILES
     internal scriptScanner(Stream file) {
            SetSource(file); // no unicode option
        }   
#endif // !NOFILES

     internal scriptScanner() { }

        private int readPos;

        void GetCode()
        {
            if (code == '\n')  // This needs to be fixed for other conventions
                               // i.e. [\r\n\205\u2028\u2029]
            { 
                cCol = -1;
                lNum++;
            }
            readPos = buffer.Pos;

            // Now read new codepoint.
            code = buffer.Read();
            if (code > ScanBuff.EndOfFile)
            {
                if (code >= 0xD800 && code <= 0xDBFF)
                {
                    int next = buffer.Read();
                    if (next < 0xDC00 || next > 0xDFFF)
                        code = ScanBuff.UnicodeReplacementChar;
                    else
                        code = (0x10000 + ((code & 0x3FF) << 10) + (next & 0x3FF));
                }
                cCol++;
            }
        }

        void MarkToken()
        {
#if (!PERSIST)
            buffer.Mark();
#endif
            tokPos = readPos;
            tokLin = lNum;
            tokCol = cCol;
        }
        
        void MarkEnd()
        {
            tokTxt = null;
            tokEPos = readPos;
            tokELin = lNum;
            tokECol = cCol;
        }

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        int Peek()
        {
            int rslt, codeSv = code, cColSv = cCol, lNumSv = lNum, bPosSv = buffer.Pos;
            GetCode(); rslt = code;
            lNum = lNumSv; cCol = cColSv; code = codeSv; buffer.Pos = bPosSv;
            return rslt;
        }

        // ==============================================================
        // =====    Initialization of string-based input buffers     ====
        // ==============================================================

        /// <summary>
        /// Create and initialize a StringBuff buffer object for this scanner
        /// </summary>
        /// <param name="source">the input string</param>
        /// <param name="offset">starting offset in the string</param>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public void SetSource(string source, int offset)
        {
            this.buffer = ScanBuff.GetBuffer(source);
            this.buffer.Pos = offset;
            this.lNum = 0;
            this.code = '\n'; // to initialize yyline, yycol and lineStart
            GetCode();
        }

        // ================ LineBuffer Initialization ===================
        /// <summary>
        /// Create and initialize a LineBuff buffer object for this scanner
        /// </summary>
        /// <param name="source">the list of input strings</param>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public void SetSource(IList<string> source)
        {
            this.buffer = ScanBuff.GetBuffer(source);
            this.code = '\n'; // to initialize yyline, yycol and lineStart
            this.lNum = 0;
            GetCode();
        }

#if !NOFILES        
        // =============== StreamBuffer Initialization ==================

        /// <summary>
        /// Create and initialize a StreamBuff buffer object for this scanner.
        /// StreamBuff is buffer for 8-bit byte files.
        /// </summary>
        /// <param name="source">the input byte stream</param>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public void SetSource(Stream source)
        {
            this.buffer = ScanBuff.GetBuffer(source);
            this.lNum = 0;
            this.code = '\n'; // to initialize yyline, yycol and lineStart
            GetCode();
        }
        
        // ================ TextBuffer Initialization ===================

        /// <summary>
        /// Create and initialize a TextBuff buffer object for this scanner.
        /// TextBuff is a buffer for encoded unicode files.
        /// </summary>
        /// <param name="source">the input text file</param>
        /// <param name="fallbackCodePage">Code page to use if file has
        /// no BOM. For 0, use machine default; for -1, 8-bit binary</param>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public void SetSource(Stream source, int fallbackCodePage)
        {
            this.buffer = ScanBuff.GetBuffer(source, fallbackCodePage);
            this.lNum = 0;
            this.code = '\n'; // to initialize yyline, yycol and lineStart
            GetCode();
        }
#endif // !NOFILES
        
        // ==============================================================

#if BABEL
        //
        //  Get the next token for Visual Studio
        //
        //  "state" is the inout mode variable that maintains scanner
        //  state between calls, using the EolState property. In principle,
        //  if the calls of EolState are costly set could be called once
        //  only per line, at the start; and get called only at the end
        //  of the line. This needs more infrastructure ...
        //
        public int GetNext(ref int state, out int start, out int end)
        {
                Token next;
            int s, e;
            s = state;        // state at start
            EolState = state;
                next = (Token)Scan();
            state = EolState;
            e = state;       // state at end;
            start = tokPos;
            end = tokEPos - 1; // end is the index of last char.
            return (int)next;
        }        
#endif // BABEL

        // ======== AbstractScanner<> Implementation =========

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "yylex")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "yylex")]
        public override int yylex()
        {
            // parserMax is set by reflecting on the Tokens
            // enumeration.  If maxParseToken is defined
            // that is used, otherwise int.MaxValue is used.
            int next;
            do { next = Scan(); } while (next >= parserMax);
            return next;
        }
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        int yypos { get { return tokPos; } }
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        int yyline { get { return tokLin; } }
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        int yycol { get { return tokCol; } }

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "yytext")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "yytext")]
        public string yytext
        {
            get 
            {
                if (tokTxt == null) 
                    tokTxt = buffer.GetString(tokPos, tokEPos);
                return tokTxt;
            }
        }

        /// <summary>
        /// Discards all but the first "n" codepoints in the recognized pattern.
        /// Resets the buffer position so that only n codepoints have been consumed;
        /// yytext is also re-evaluated. 
        /// </summary>
        /// <param name="n">The number of codepoints to consume</param>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        void yyless(int n)
        {
            buffer.Pos = tokPos;
            // Must read at least one char, so set before start.
            cCol = tokCol - 1; 
            GetCode();
            // Now ensure that line counting is correct.
            lNum = tokLin;
            // And count the rest of the text.
            for (int i = 0; i < n; i++) GetCode();
            MarkEnd();
        }
       
        //
        //  It would be nice to count backward in the text
        //  but it does not seem possible to re-establish
        //  the correct column counts except by going forward.
        //
        /// <summary>
        /// Removes the last "n" code points from the pattern.
        /// </summary>
        /// <param name="n">The number to remove</param>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        void _yytrunc(int n) { yyless(yyleng - n); }
        
        //
        // This is painful, but we no longer count
        // codepoints.  For the overwhelming majority 
        // of cases the single line code is fast, for
        // the others, well, at least it is all in the
        // buffer so no files are touched. Note that we
        // can't use (tokEPos - tokPos) because of the
        // possibility of surrogate pairs in the token.
        //
        /// <summary>
        /// The length of the pattern in codepoints (not the same as 
        /// string-length if the pattern contains any surrogate pairs).
        /// </summary>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "yyleng")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "yyleng")]
        public int yyleng
        {
            get {
                if (tokELin == tokLin)
                    return tokECol - tokCol;
                else
                {
                    int ch;
                    int count = 0;
                    int save = buffer.Pos;
                    buffer.Pos = tokPos;
                    do {
                        ch = buffer.Read();
                        if (!char.IsHighSurrogate((char)ch)) count++;
                    } while (buffer.Pos < tokEPos && ch != ScanBuff.EndOfFile);
                    buffer.Pos = save;
                    return count;
                }
            }
        }
        
        // ============ methods available in actions ==============

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal int YY_START {
            get { return currentScOrd; }
            set { currentScOrd = value; 
                  currentStart = startState[value]; 
            } 
        }
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal void BEGIN(int next) {
            currentScOrd = next;
            currentStart = startState[next];
        }

        // ============== The main tokenizer code =================

        int Scan() {
                for (; ; ) {
                    int next;              // next state to enter
#if LEFTANCHORS
                    for (;;) {
                        // Discard characters that do not start any pattern.
                        // Must check the left anchor condition after *every* GetCode!
                        state = ((cCol == 0) ? anchorState[currentScOrd] : currentStart);
                        if ((next = NextState()) != goStart) break; // LOOP EXIT HERE...
                        GetCode();
                    }
                    
#else // !LEFTANCHORS
                    state = currentStart;
                    while ((next = NextState()) == goStart) {
                        // At this point, the current character has no
                        // transition from the current state.  We discard 
                        // the "no-match" char.   In traditional LEX such 
                        // characters are echoed to the console.
                        GetCode();
                    }
#endif // LEFTANCHORS                    
                    // At last, a valid transition ...    
                    MarkToken();
                    state = next;
                    GetCode();                    
#if BACKUP
                    bool contextSaved = false;
                    while ((next = NextState()) > eofNum) { // Exit for goStart AND for eofNum
                        if (state <= maxAccept && next > maxAccept) { // need to prepare backup data
                            // Store data for the *latest* accept state that was found.
                            SaveStateAndPos( ref ctx );
                            contextSaved = true;
                        }
                        state = next;
                        GetCode();
                    }
                    if (state > maxAccept && contextSaved)
                        RestoreStateAndPos( ref ctx );
#else  // BACKUP
                    while ((next = NextState()) > eofNum) { // Exit for goStart AND for eofNum
                         state = next;
                         GetCode();
                    }
#endif // BACKUP
                    if (state <= maxAccept) {
                        MarkEnd();
#region ActionSwitch
#pragma warning disable 162, 1522
    switch (state)
    {
        case eofNum:
            if (yywrap())
                return (int)Token.EOF;
            break;
        case 1: // Recognized '{Space}+',	Shortest string "\t"
/* skip */
            break;
        case 2: // Recognized '{LParen}',	Shortest string "("
return (int)Token.LPAREN;
            break;
        case 3: // Recognized '{RParen}',	Shortest string ")"
return (int)Token.RPAREN;
            break;
        case 4: // Recognized '{Number}',	Shortest string "0"
        case 5: // Recognized '{Number}',	Shortest string "1"
        case 71: // Recognized '{Number}',	Shortest string "0x0"
yylval.s = yytext; return (int)Token.TDIGIT;
            break;
        case 6: // Recognized '{TLess}',	Shortest string "<"
return (int)Token.TLESSTHAN;
            break;
        case 7: // Recognized '{TEquals}',	Shortest string "="
return (int)Token.TEQUALS;
            break;
        case 8: // Recognized '{TGreater}',	Shortest string ">"
return (int)Token.TGREATERTHAN;
            break;
        case 9: // Recognized '{Identifier}',	Shortest string "A"
        case 10: // Recognized '{Identifier}',	Shortest string "B"
        case 11: // Recognized '{Identifier}',	Shortest string "C"
        case 12: // Recognized '{Identifier}',	Shortest string "E"
        case 13: // Recognized '{Identifier}',	Shortest string "G"
        case 14: // Recognized '{Identifier}',	Shortest string "I"
        case 15: // Recognized '{Identifier}',	Shortest string "N"
        case 16: // Recognized '{Identifier}',	Shortest string "R"
        case 17: // Recognized '{Identifier}',	Shortest string "S"
        case 18: // Recognized '{Identifier}',	Shortest string "T"
        case 19: // Recognized '{Identifier}',	Shortest string "X"
        case 20: // Recognized '{Identifier}',	Shortest string "e"
        case 21: // Recognized '{Identifier}',	Shortest string "l"
        case 25: // Recognized '{Identifier}',	Shortest string "TH"
        case 26: // Recognized '{Identifier}',	Shortest string "THE"
        case 28: // Recognized '{Identifier}',	Shortest string "SE"
        case 30: // Recognized '{Identifier}',	Shortest string "RE"
        case 31: // Recognized '{Identifier}',	Shortest string "RO"
        case 32: // Recognized '{Identifier}',	Shortest string "ROL"
        case 33: // Recognized '{Identifier}',	Shortest string "ROLL"
        case 34: // Recognized '{Identifier}',	Shortest string "ROLLB"
        case 35: // Recognized '{Identifier}',	Shortest string "ROLLBA"
        case 36: // Recognized '{Identifier}',	Shortest string "ROLLBAC"
        case 38: // Recognized '{Identifier}',	Shortest string "RET"
        case 39: // Recognized '{Identifier}',	Shortest string "RETU"
        case 40: // Recognized '{Identifier}',	Shortest string "RETUR"
        case 43: // Recognized '{Identifier}',	Shortest string "EL"
        case 44: // Recognized '{Identifier}',	Shortest string "ELS"
        case 47: // Recognized '{Identifier}',	Shortest string "GE"
        case 49: // Recognized '{Identifier}',	Shortest string "EG"
        case 50: // Recognized '{Identifier}',	Shortest string "EN"
        case 51: // Recognized '{Identifier}',	Shortest string "ES"
        case 53: // Recognized '{Identifier}',	Shortest string "ESE"
        case 56: // Recognized '{Identifier}',	Shortest string "EGE"
        case 58: // Recognized '{Identifier}',	Shortest string "CO"
        case 59: // Recognized '{Identifier}',	Shortest string "COM"
        case 60: // Recognized '{Identifier}',	Shortest string "COMI"
        case 62: // Recognized '{Identifier}',	Shortest string "BE"
        case 63: // Recognized '{Identifier}',	Shortest string "BEG"
        case 64: // Recognized '{Identifier}',	Shortest string "BEGI"
yylval.s = yytext; return (int)Token.TIDENTIFIER;
            break;
        case 22: // Recognized '{LBrace}',	Shortest string "{"
return (int)Token.LBRACE;
            break;
        case 23: // Recognized '{RBrace}',	Shortest string "}"
return (int)Token.RBRACE;
            break;
        case 24: // Recognized '{TXx}',	Shortest string "XX"
return (int)Token.TXX;
            break;
        case 27: // Recognized '{TThen}',	Shortest string "THEN"
return (int)Token.TTHEN;
            break;
        case 29: // Recognized '{TSet}',	Shortest string "SET"
return (int)Token.TSET;
            break;
        case 37: // Recognized '{TRollback}',	Shortest string "ROLLBACK"
return (int)Token.TROLLBACK;
            break;
        case 41: // Recognized '{TReturn}',	Shortest string "RETURN"
return (int)Token.TRETURN;
            break;
        case 42: // Recognized '{TNx}',	Shortest string "NX"
return (int)Token.TNX;
            break;
        case 45: // Recognized '{TElse}',	Shortest string "ELSE"
return (int)Token.TELSE;
            break;
        case 46: // Recognized '{TIf}',	Shortest string "IF"
return (int)Token.TIF;
            break;
        case 48: // Recognized '{TGet}',	Shortest string "GET"
return (int)Token.TGET;
            break;
        case 52: // Recognized '{TEx}',	Shortest string "EX"
return (int)Token.TEX;
            break;
        case 54: // Recognized '{TEset}',	Shortest string "ESET"
return (int)Token.TESET;
            break;
        case 55: // Recognized '{TEnd}',	Shortest string "END"
return (int)Token.TEND;
            break;
        case 57: // Recognized '{TEget}',	Shortest string "EGET"
return (int)Token.TEGET;
            break;
        case 61: // Recognized '{TCommit}',	Shortest string "COMIT"
return (int)Token.TCOMMIT;
            break;
        case 65: // Recognized '{TBegin}',	Shortest string "BEGIN"
return (int)Token.TBEGIN;
            break;
        case 66: // Recognized '{Placeholder}',	Shortest string "@0"
yylval.s = yytext; return (int)Token.TPLACEHOLDER;
            break;
        case 67: // Recognized '{TGreaterEquals}',	Shortest string ">="
return (int)Token.TGREATERTHANEQUALS;
            break;
        case 68: // Recognized '{TLessEquals}',	Shortest string "<="
return (int)Token.TLESSTHANEQUALS;
            break;
        case 69: // Recognized '{TNotEquals}',	Shortest string "<>"
return (int)Token.TNOTEQUALS;
            break;
        case 70: // Recognized '{Decimal}',	Shortest string "0.0"
yylval.s = yytext; return (int)Token.TFLOAT;
            break;
        case 72: // Recognized '{StringSingle}',	Shortest string "''"
yylval.s = yytext; return (int)Token.TSTRING;
            break;
        case 73: // Recognized '{String}',	Shortest string "\"\""
yylval.s = yytext; return (int)Token.TSTRING;
            break;
        case 74: // Recognized '{TNotEquals2}',	Shortest string "!="
return (int)Token.TNOTEQUALS;
            break;
        default:
            break;
    }
#pragma warning restore 162, 1522
#endregion
                    }
                }
        }

#if BACKUP
        void SaveStateAndPos(ref Context ctx) {
            ctx.bPos  = buffer.Pos;
            ctx.rPos  = readPos;
            ctx.cCol  = cCol;
            ctx.lNum  = lNum;
            ctx.state = state;
            ctx.cChr  = code;
        }

        void RestoreStateAndPos(ref Context ctx) {
            buffer.Pos = ctx.bPos;
            readPos = ctx.rPos;
            cCol  = ctx.cCol;
            lNum  = ctx.lNum;
            state = ctx.state;
            code  = ctx.cChr;
        }
#endif  // BACKUP

        // ============= End of the tokenizer code ================

#if STACK        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal void yy_clear_stack() { scStack.Clear(); }
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal int yy_top_state() { return scStack.Peek(); }
        
        internal void yy_push_state(int state)
        {
            scStack.Push(currentScOrd);
            BEGIN(state);
        }
        
        internal void yy_pop_state()
        {
            // Protect against input errors that pop too far ...
            if (scStack.Count > 0) {
				int newSc = scStack.Pop();
				BEGIN(newSc);
            } // Otherwise leave stack unchanged.
        }
 #endif // STACK

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal void ECHO() { Console.Out.Write(yytext); }
        
    } // end class $Scanner


} // end namespace
