
using Kahuna.Shared.KeyValue;
using Kahuna.Shared.Sequences;
using System.Text.Json.Serialization;

namespace Kahuna.Shared.Communication.Rest;

[JsonSerializable(typeof(KahunaGetLockRequest))]
[JsonSerializable(typeof(KahunaGetLockResponse))]
[JsonSerializable(typeof(KahunaLockRequest))]
[JsonSerializable(typeof(KahunaExistsKeyValueRequest))]
[JsonSerializable(typeof(KahunaGetLockResponse))]
[JsonSerializable(typeof(KahunaSetKeyValueRequest))]
[JsonSerializable(typeof(KahunaGetKeyValueRequest))]
[JsonSerializable(typeof(KahunaDeleteKeyValueRequest))]
[JsonSerializable(typeof(KahunaSetManyKeyValueRequest))]
[JsonSerializable(typeof(KahunaSetManyKeyValueResponse))]
[JsonSerializable(typeof(KahunaDeleteManyKeyValueRequest))]
[JsonSerializable(typeof(KahunaDeleteManyKeyValueResponse))]
[JsonSerializable(typeof(KahunaExtendKeyValueRequest))]
[JsonSerializable(typeof(KahunaDeleteKeyValueRequestItem))]
[JsonSerializable(typeof(KahunaDeleteKeyValueResponseItem))]
[JsonSerializable(typeof(KeyValueTransactionRequest))]
[JsonSerializable(typeof(KahunaSequenceCreateRequest))]
[JsonSerializable(typeof(KahunaSequenceNameRequest))]
[JsonSerializable(typeof(KahunaSequenceNextRequest))]
[JsonSerializable(typeof(KahunaSequenceReserveRequest))]
[JsonSerializable(typeof(KahunaSequenceResponse))]
[JsonSerializable(typeof(ReadOnlySequenceEntry))]
[JsonSerializable(typeof(SequenceAllocation))]
[JsonSerializable(typeof(KahunaClusterMembershipResponse))]
[JsonSerializable(typeof(KahunaClusterHealthResponse))]
[JsonSerializable(typeof(KahunaClusterLeaveResponse))]
[JsonSerializable(typeof(KahunaClusterMemberResponse))]
[JsonSerializable(typeof(List<KahunaClusterMemberResponse>))]
[JsonSerializable(typeof(KahunaClusterPlacementResponse))]
[JsonSerializable(typeof(KahunaPartitionPlacementResponse))]
[JsonSerializable(typeof(List<KahunaPartitionPlacementResponse>))]
[JsonSerializable(typeof(KahunaPartitionReplicaResponse))]
[JsonSerializable(typeof(List<KahunaPartitionReplicaResponse>))]
[JsonSerializable(typeof(KahunaDashboardSummaryResponse))]
[JsonSerializable(typeof(KahunaDashboardMetricsResponse))]
[JsonSerializable(typeof(KahunaDashboardMetricRow))]
[JsonSerializable(typeof(List<KahunaDashboardMetricRow>))]
[JsonSerializable(typeof(KahunaSetReplicationFactorRequest))]
[JsonSerializable(typeof(KahunaSetReplicationFactorResponse))]
[JsonSerializable(typeof(KahunaRangeMapResponse))]
[JsonSerializable(typeof(KahunaKeySpaceRangesResponse))]
[JsonSerializable(typeof(List<KahunaKeySpaceRangesResponse>))]
[JsonSerializable(typeof(KahunaRangeDescriptorResponse))]
[JsonSerializable(typeof(List<KahunaRangeDescriptorResponse>))]
[JsonSerializable(typeof(KahunaKeyRangeRequest))]
[JsonSerializable(typeof(KahunaRegisterKeyRangeResponse))]
[JsonSerializable(typeof(KahunaRemoveKeyRangeResponse))]
[JsonSerializable(typeof(KahunaSplitRangeRequest))]
[JsonSerializable(typeof(KahunaSplitRangeResponse))]
[JsonSerializable(typeof(KahunaMergeRangesResponse))]
[JsonSerializable(typeof(KahunaBackupInfo))]
[JsonSerializable(typeof(List<KahunaBackupInfo>))]
[JsonSerializable(typeof(KahunaBackupIncrementalRequest))]
[JsonSerializable(typeof(KahunaBackupRestoreRequest))]
[JsonSerializable(typeof(KahunaRestoreResponse))]
[JsonSerializable(typeof(KahunaBackupGcResult))]
[JsonSerializable(typeof(KahunaBackupGcDeletion))]
[JsonSerializable(typeof(KahunaBackupGcOrphan))]
[JsonSerializable(typeof(KahunaAcquireSnapshotHoldRequest))]
[JsonSerializable(typeof(KahunaAcquireSnapshotHoldResponse))]
[JsonSerializable(typeof(KahunaRenewSnapshotHoldRequest))]
[JsonSerializable(typeof(KahunaRenewSnapshotHoldResponse))]
[JsonSerializable(typeof(KahunaReleaseSnapshotHoldRequest))]
[JsonSerializable(typeof(KahunaReleaseSnapshotHoldResponse))]
[JsonSerializable(typeof(KahunaGetSnapshotFloorResponse))]
[JsonSerializable(typeof(KahunaManyKeyValuesRequest))]
[JsonSerializable(typeof(KahunaManyKeyValuesResponse))]
[JsonSerializable(typeof(KahunaGetManyKeyValuesRequestItem))]
[JsonSerializable(typeof(KahunaGetManyKeyValuesResponseItem))]
[JsonSerializable(typeof(KahunaGetByRangeRequest))]
[JsonSerializable(typeof(KahunaGetByRangeResponse))]
[JsonSerializable(typeof(KahunaGetByBucketRequest))]
[JsonSerializable(typeof(KahunaGetByBucketResponse))]
[JsonSerializable(typeof(KahunaScanAllByPrefixRequest))]
[JsonSerializable(typeof(KeyValueGetByBucketItem))]
[JsonSerializable(typeof(List<KeyValueGetByBucketItem>))]
[JsonSerializable(typeof(KahunaAcquireKeyValueLockRequest))]
[JsonSerializable(typeof(KahunaReleaseKeyValueLockRequest))]
[JsonSerializable(typeof(KahunaKeyValueLockResponse))]
[JsonSerializable(typeof(KahunaAcquireRangeLockRequest))]
[JsonSerializable(typeof(KahunaReleaseRangeLockRequest))]
[JsonSerializable(typeof(KahunaStartTransactionRequest))]
[JsonSerializable(typeof(KahunaStartTransactionResponse))]
[JsonSerializable(typeof(KahunaCommitTransactionRequest))]
[JsonSerializable(typeof(KahunaCommitTransactionResponse))]
[JsonSourceGenerationOptions(PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase)]
public sealed partial class KahunaJsonContext : JsonSerializerContext
{

}
