name: Run Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  Kahuna-Tests:
    runs-on: ubuntu-latest
    env:
      GIT_BRANCH: ${{ github.head_ref || github.ref_name }}
      GIT_COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
      KAHUNA_SERVER_DEFAULT_LOG_LEVEL: Warning
      KAHUNA_SERVER_LOG_LEVEL: Error
      KAHUNA_TEST_LOG_LEVEL: Error
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
        with:
          fetch-depth: 2
      - name: Install .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
            8.0.x
            9.0.x
      - name: Run Kahuna Server
        run: (cd scripts && chmod +x ./run-server.sh && ./run-server.sh)
      - name: Run Client Tests
        run: (cd Kahuna.Tests && dotnet test -l "console;verbosity=normal" --blame-hang --blame-hang-timeout 10m --blame-hang-dump-type none --filter "FullyQualifiedName~Kahuna.Tests.Client")
      - name: Stop Kahuna Server
        if: always()
        run: docker compose -f docker/local.yml down -v
      - name: Run Server Tests
        run: (cd Kahuna.Tests && dotnet test -l "console;verbosity=normal" --blame-hang --blame-hang-timeout 10m --blame-hang-dump-type none --filter "FullyQualifiedName~Kahuna.Tests.Server")
